name: CI for Hello World

on:
  push:
    branches: [main]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Libraries
      run: |
        pip install pytest
        pip install flake8 pytest pytest-cov robotframework

    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with:
        repository: leonlti/python-calculator

    #- name: Get TestScript from Remote Repository
      #env:
        #TOKEN: ${{ secrets.benrepo }} #secrets.repo_token
      #run: |
      #  curl -H "Authorization: token ${TOKEN}" https://raw.githubusercontent.com/leonlti/python-calculator/main/test_calculator.py -o test_calculator.py

    - name: Start pytest Testing
      run: |
        pytest test_calculator.py -v -cov --junitxml=report.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        junit_files: "report.xml"
