name: Simple Start Up
on:
    push:
        branches: [main]

jobs:
    build:

        name: Build my virtual OS

        runs-on: ubuntu-latest

        steps:

        - name: checkout my codes
          uses: actions/checkout@v2

        - name: Print and list out content
          run: |
            ls
            echo Hello There!

        - name: Checkout private repo remotely
          uses: actions/checkout@v2
          with:
            repository: lowkh/hiddenRepo
            #path: <folder of choice>
            token: ${{ secrets.benrepo }}

        - name: Show hidden files
          run: |
            ls -alch
            cat README.md

       
